# Site settings
title: Edward Ding's Blog
email: holmes93@163.com
description: "Great ideas come from every day's accumulation."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: Not work in China :(
github_username:  EdwardDing

# Build settings
markdown: kramdown
permalink: pretty
