# Site settings
title: Edward Ding's Blog
email: holmes93@163.com
description: "People can't come up with new ideas from no where, only from everyday's accumulation"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: Not work in China :(
github_username:  EdwardDing

# Build settings
markdown: kramdown
permalink: pretty

# Other settings
comments: true